name: CI

on:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Install packages
      run: |
        cd test-actions
        yarn install
    - name: Run tests
      run: |
        cd test-actions
        yarn test
