name: Node CI

on: [push]

jobs:
  build:
    env:
      appdir: test-actions

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install packages
        run: |
          cd ${appdir}
          yarn install
      - name: check info
        run: |
          pwd
          ls -la
          echo ${HOME}
          echo ${GITHUB_WORKSPACE}
      - name: run tests
        run: |
          cd ${appdir}
          yarn test
